"""empty message

Revision ID: 7f9cc2c94c4a
Revises: 6af87ec9757b
Create Date: 2018-08-30 13:02:36.865973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9cc2c94c4a'
down_revision = '6af87ec9757b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'user_id')
    # ### end Alembic commands ###
