"""empty message

Revision ID: 9944c1233f01
Revises: 
Create Date: 2018-07-09 11:52:28.944611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9944c1233f01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    op.drop_constraint('ingredient_ingredient_name_key', 'ingredient', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ingredient_ingredient_name_key', 'ingredient', ['ingredient_name'])
    op.create_table('step',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='step_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='step_pkey')
    )
    # ### end Alembic commands ###
