"""empty message

Revision ID: a9ae485e0ad0
Revises: 9944c1233f01
Create Date: 2018-07-10 21:38:33.146898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ae485e0ad0'
down_revision = '9944c1233f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredient', ['ingredient_name'])
    op.drop_constraint('method_recipe_id_fkey', 'method', type_='foreignkey')
    op.create_foreign_key(None, 'method', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quantity_recipe_id_fkey', 'quantity', type_='foreignkey')
    op.create_foreign_key(None, 'quantity', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.add_column('recipe', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('recipe', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image_url')
    op.drop_column('recipe', 'image_filename')
    op.drop_constraint(None, 'quantity', type_='foreignkey')
    op.create_foreign_key('quantity_recipe_id_fkey', 'quantity', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'method', type_='foreignkey')
    op.create_foreign_key('method_recipe_id_fkey', 'method', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'ingredient', type_='unique')
    # ### end Alembic commands ###
