"""empty message

Revision ID: cdd5c936faf0
Revises: a9ae485e0ad0
Create Date: 2018-07-26 16:30:24.587444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd5c936faf0'
down_revision = 'a9ae485e0ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_ingredient_name_key', 'ingredient', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ingredient_ingredient_name_key', 'ingredient', ['ingredient_name'])
    # ### end Alembic commands ###
